#uri: http://localhost:8082
spring:
  cloud:
    gateway:
      routes:
      - id: r1
        uri: lb://SCORE-SERVICE
        predicates:
        - Path= /api/result/**
      - id: r2
        uri: http://localhost:8000
        predicates:
        - Path= /api/result/**
                  